"""
Waitlist — pre-launch email capture for the access gate.

Endpoints
---------
POST /api/waitlist          — unauth'd; { email, source? } → creates/updates
GET  /api/waitlist/count    — unauth'd; { count: N }

Launch-day hardening
--------------------
• Confirmation email via Resend (with the "Using Marvex Studio" PDF attached)
  fires after every NEW signup. Re-submits don't re-send the email.
• Per-IP rate limit: at most 5 signups per minute from the same address,
  enforced via an in-memory sliding-window counter. Survives the typical
  share-on-Reddit traffic spike without needing Redis.
• Email failures NEVER block the API response — we always tell the user
  "you're on the list" and log the email error for our own debugging.

Design notes
------------
• Deduplicates by email (normalised, lowercase). Second submit updates the
  source field but doesn't double-count and doesn't re-email.
• The admin exports via `db.waitlist.find()` when ready to launch.
"""

import asyncio
import logging
import re
import time
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from motor.motor_asyncio import AsyncIOMotorDatabase
from pydantic import BaseModel, Field

from email_sender import send_email

logger = logging.getLogger(__name__)

EMAIL_RE = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")

# Per-IP sliding window (in seconds). Cheap and adequate for a launch day.
_RATE_WINDOW_S = 60
_RATE_MAX_HITS = 5
_recent_hits: dict[str, deque] = defaultdict(deque)

# Welcome PDF path — generated by /app/backend/scripts/build_welcome_pdf.py
WELCOME_PDF = Path(__file__).parent / "assets" / "using-marvex.pdf"


def _client_ip(req: Request) -> str:
    """Best-effort client IP. Honours the X-Forwarded-For header that the
    Kubernetes ingress prepends, falls back to the direct peer."""
    xff = req.headers.get("x-forwarded-for", "")
    if xff:
        # XFF is a comma-separated list — the first entry is the original.
        return xff.split(",")[0].strip()
    return req.client.host if req.client else "unknown"


def _rate_limited(ip: str) -> bool:
    now = time.time()
    bucket = _recent_hits[ip]
    # Evict timestamps older than the window
    while bucket and now - bucket[0] > _RATE_WINDOW_S:
        bucket.popleft()
    if len(bucket) >= _RATE_MAX_HITS:
        return True
    bucket.append(now)
    return False


def _welcome_html(email: str) -> str:
    """Lightweight, table-based HTML — survives Outlook + Gmail mobile.

    Deliberately understated: pure dark background with cyan accents, NO
    gradient buttons, NO marketing-style emoji, NO "FREE PDF!!" energy.
    Outlook and Gmail's first-impression spam filters reward plain
    transactional aesthetics; we earn the inbox first, then we ship
    flashier broadcasts later.
    """
    safe_email = email.replace("<", "&lt;").replace(">", "&gt;")
    return f"""\
<!doctype html>
<html><body style="margin:0;background:#0a0f24;font-family:Helvetica,Arial,sans-serif;color:#e6edf7;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0a0f24;padding:28px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;background:#0a0f24;">
        <tr><td style="padding:8px 8px 18px 8px;">
          <h1 style="margin:0 0 18px 0;font-size:24px;line-height:30px;color:#ffffff;font-weight:600;">
            Welcome to Marvex Studio.
          </h1>
          <p style="margin:0 0 14px 0;font-size:15px;line-height:24px;color:#cfdaf3;">
            Hi — thanks for joining the early-access list for marvex.app.
            We'll email you the moment the Studio opens to founding members.
          </p>
          <p style="margin:0 0 14px 0;font-size:15px;line-height:24px;color:#cfdaf3;">
            In the meantime, your starter guide is attached to this email:
            <strong style="color:#ffffff;">Using Marvex Studio</strong>, an
            8-chapter pocket manual covering the right-click magic, BYOK
            setup, the global search, smart link routing, the calendar
            view, and every keyboard shortcut you'll ever need.
          </p>
          <p style="margin:18px 0 8px 0;font-size:14px;line-height:22px;color:#cfdaf3;">
            Visit the site any time:
            <a href="https://marvex.app" style="color:#00b8cc;text-decoration:underline;">marvex.app</a>
          </p>
          <p style="margin:14px 0 0 0;font-size:14px;line-height:22px;color:#cfdaf3;">
            Reply to this email any time — it lands in our inbox and gets
            read the same day.
          </p>
          <p style="margin:22px 0 0 0;font-size:14px;line-height:22px;color:#9aaad0;">
            — The Marvex Studio team
          </p>
        </td></tr>
        <tr><td style="padding:18px 8px 0 8px;border-top:1px solid rgba(255,255,255,0.08);">
          <div style="font-size:11px;line-height:18px;color:#566187;">
            You're receiving this because <strong style="color:#9aaad0;">{safe_email}</strong>
            was entered on the marvex.app waitlist form.
            To unsubscribe, just reply with the word <em>remove</em> in the subject line.
          </div>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>
"""


class WaitlistJoin(BaseModel):
    email: str = Field(..., max_length=320)
    source: Optional[str] = Field(None, max_length=80)


def make_router(db: AsyncIOMotorDatabase) -> APIRouter:
    router = APIRouter(prefix="/api/waitlist")

    @router.post("")
    async def join(payload: WaitlistJoin, request: Request):
        ip = _client_ip(request)
        if _rate_limited(ip):
            logger.warning("waitlist rate-limit hit from %s", ip)
            raise HTTPException(
                status_code=429,
                detail="You're going a little fast. Please try again in a minute.",
            )

        email = payload.email.strip().lower()
        if not EMAIL_RE.match(email):
            raise HTTPException(status_code=400, detail="Please enter a valid email address")

        now = datetime.now(timezone.utc)
        # Atomic upsert lets us tell whether this is a NEW signup (and
        # therefore whether to send the welcome email) without a race
        # window between read and write.
        result = await db.waitlist.update_one(
            {"email": email},
            {
                "$setOnInsert": {"created_at": now, "welcomed": False},
                "$set": {"source": (payload.source or "landing")[:80], "last_seen": now},
            },
            upsert=True,
        )
        is_new = result.upserted_id is not None
        total = await db.waitlist.count_documents({})

        # Fire the welcome email asynchronously — never block the response on
        # email delivery. If it succeeds, mark `welcomed=True` so we don't
        # re-send on subsequent submits even if the user clears their
        # localStorage and rejoins.
        if is_new:
            asyncio.create_task(_send_welcome(db, email))

        return {"ok": True, "count": total, "new": is_new}

    @router.get("/count")
    async def count():
        total = await db.waitlist.count_documents({})
        return {"count": total}

    return router


async def _send_welcome(db: AsyncIOMotorDatabase, email: str) -> None:
    """Background task: send the confirmation email + PDF, then record the
    delivery status on the user's waitlist row.

    `reply_to` defaults to `support@marvex.app` so anyone who replies
    to the welcome email lands in the support helper's mailbox, not in
    the no-reply Resend address. Override via `WAITLIST_REPLY_TO` env
    if your routing changes.
    """
    import os as _os
    reply_to = _os.environ.get("WAITLIST_REPLY_TO") or "support@marvex.app"
    try:
        result = await send_email(
            to=email,
            subject="Welcome to Marvex Studio — your starter guide is inside",
            html=_welcome_html(email),
            attachments=[WELCOME_PDF] if WELCOME_PDF.exists() else None,
            reply_to=reply_to,
        )
        await db.waitlist.update_one(
            {"email": email},
            {"$set": {
                "welcomed": bool(result.get("ok")),
                "welcome_status": result,
                "welcomed_at": datetime.now(timezone.utc),
            }},
        )
    except Exception:
        logger.exception("welcome-email background task crashed for %s", email)
