import React, { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Search, Highlighter, FileText, ExternalLink, Copy, Bookmark, Download } from "lucide-react";
import { toast } from "sonner";
import { listMaps, addToRecents } from "@/lib/storage";
import Logo from "@/components/Logo";
import usePageMeta from "@/lib/usePageMeta";

/**
 * Personal knowledge ledger — aggregates every passage the user has ever
 * highlighted-to-map across every map's readerMeta.highlights[]. One search
 * box filters by text. One dropdown filters by source PDF. Click any row to
 * open the owning map.
 */
export default function Highlights() {
  const navigate = useNavigate();
  const [query, setQuery] = useState("");
  const [pdfFilter, setPdfFilter] = useState("");
  usePageMeta({
    title: "Highlights · Marvex Studio",
    description: "Every passage you've ever highlighted-to-map, in one searchable ledger. Filter by source PDF, export to Markdown, click any row to jump back to the owning map.",
    type: "website",
  });

  // Flatten every highlight across every map (one pass).
  const all = useMemo(() => {
    const rows = [];
    for (const m of listMaps()) {
      const highs = m.readerMeta?.highlights || [];
      for (const h of highs) {
        rows.push({
          ...h,
          mapId: m.id,
          mapTitle: m.title,
        });
      }
    }
    rows.sort((a, b) => (b.ts || 0) - (a.ts || 0));
    return rows;
  }, []);

  // Every distinct PDF (by fileName) → used for the filter dropdown.
  const pdfs = useMemo(() => {
    const seen = new Map();
    for (const h of all) {
      const name = h.fileName || "Unknown";
      seen.set(name, (seen.get(name) || 0) + 1);
    }
    return Array.from(seen.entries()).sort((a, b) => b[1] - a[1]);
  }, [all]);

  // Applied filters.
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return all.filter((h) => {
      if (pdfFilter && h.fileName !== pdfFilter) return false;
      if (q && !(h.text || "").toLowerCase().includes(q)) return false;
      return true;
    });
  }, [all, query, pdfFilter]);

  const open = (h) => {
    addToRecents(h.mapId);
    navigate(`/app?map=${h.mapId}&focus=${h.nodeId}`);
  };

  const exportMarkdown = () => {
    if (!filtered.length) return;
    const today = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
    const header = `# My highlights · ${today}\n\n*${filtered.length} highlight${filtered.length === 1 ? "" : "s"} exported from marvex.app*\n\n`;

    // Group by source PDF.
    const groups = new Map();
    for (const h of filtered) {
      const key = h.fileName || "Unknown source";
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push(h);
    }

    const sections = Array.from(groups.entries()).map(([pdf, rows]) => {
      const body = rows.map((h) => {
        const date = h.ts ? new Date(h.ts).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "";
        const page = h.pageNumber != null ? ` · p. ${h.pageNumber}` : "";
        const quote = (h.text || "").split("\n").map((l) => `> ${l}`).join("\n");
        return `${quote}\n>\n> — from **${h.mapTitle}**${page}${date ? ` · ${date}` : ""}\n`;
      }).join("\n");
      return `## ${pdf}\n\n${body}`;
    }).join("\n");

    const footer = `\n---\n*Generated by [marvex.app](https://marvex.app) · Turn any PDF into a mind-map*\n`;
    const blob = new Blob([header + sections + footer], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `mindmapper-highlights-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Exported ${filtered.length} highlight${filtered.length === 1 ? "" : "s"}`);
  };

  return (
    <div className="min-h-screen bg-[#03040a] text-[#cfdaf3]">
      {/* Header */}
      <header className="px-6 md:px-10 h-16 flex items-center gap-4 border-b border-white/10 bg-[#04060d] sticky top-0 z-30">
        <button
          onClick={() => navigate(-1)}
          data-testid="highlights-back"
          className="mono text-[10px] uppercase tracking-[0.22em] text-[#9aa7c7] hover:text-cyan-300 flex items-center gap-1.5"
        >
          <ArrowLeft size={12} /> Back
        </button>
        <div className="h-6 w-px bg-white/10" />
        <Logo size={30} />
        <div>
          <div className="mono text-[10px] uppercase tracking-[0.22em] text-cyan-300/80">
            Highlights
          </div>
          <div className="mono text-[9px] uppercase tracking-[0.18em] text-[#566187]">
            Your reading ledger
          </div>
        </div>
      </header>

      <main className="px-6 md:px-10 py-10 max-w-5xl mx-auto" data-testid="highlights-page">
        {/* Hero */}
        <section className="mb-8">
          <div className="mono text-[10px] uppercase tracking-[0.25em] text-cyan-300/80 mb-2">
            Every passage you&apos;ve mapped · sorted by recency
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-white leading-tight mb-4">
            <span className="gradient-text">{all.length}</span> highlights across{" "}
            <span className="gradient-text">{pdfs.length}</span> PDF{pdfs.length === 1 ? "" : "s"}
          </h1>
          <p className="text-[14px] text-[#9aa7c7] max-w-2xl leading-relaxed">
            Every time you map a passage from the PDF Reader, it lands here. Search, filter by
            source, and jump straight to the node where it lives.
          </p>
        </section>

        {/* Filters */}
        <section className="flex flex-col md:flex-row gap-3 mb-6">
          <div className="flex-1 relative">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#566187]" />
            <input
              data-testid="highlights-search"
              type="search"
              placeholder="Search highlight text…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="w-full bg-[#0a0f24] border border-white/10 rounded-lg pl-9 pr-3 py-2.5 text-[13px] text-white placeholder-[#566187] focus:outline-none focus:border-cyan-400/60 transition"
            />
          </div>
          {pdfs.length > 1 && (
            <select
              data-testid="highlights-pdf-filter"
              value={pdfFilter}
              onChange={(e) => setPdfFilter(e.target.value)}
              className="bg-[#0a0f24] border border-white/10 rounded-lg px-3 py-2.5 text-[13px] text-white min-w-[200px] focus:outline-none focus:border-cyan-400/60"
            >
              <option value="">{`All PDFs (${all.length})`}</option>
              {pdfs.map(([name, count]) => (
                <option key={name} value={name}>{`${name} · ${count}`}</option>
              ))}
            </select>
          )}
          {filtered.length > 0 && (
            <button
              onClick={exportMarkdown}
              data-testid="highlights-export-md"
              title="Download as Markdown"
              className="mono text-[10px] uppercase tracking-[0.22em] px-4 py-2.5 rounded-lg border border-cyan-400/40 text-cyan-200 hover:bg-cyan-400/10 transition flex items-center justify-center gap-1.5 shrink-0"
            >
              <Download size={12} /> Markdown
            </button>
          )}
        </section>

        {/* Empty states */}
        {all.length === 0 && (
          <EmptyHero onGo={() => navigate("/read")} />
        )}
        {all.length > 0 && filtered.length === 0 && (
          <div
            data-testid="highlights-empty-filtered"
            className="text-center py-16 text-[#7a87ad] text-[14px]"
          >
            No highlights match that filter.
          </div>
        )}

        {/* List */}
        {filtered.length > 0 && (
          <ul className="space-y-3" data-testid="highlights-list">
            {filtered.map((h) => (
              <li
                key={`${h.mapId}-${h.nodeId}`}
                data-testid="highlights-item"
                onClick={() => open(h)}
                className="group rounded-xl border border-white/10 bg-white/[0.02] px-5 py-4 cursor-pointer transition-all hover:border-cyan-400/40 hover:bg-white/[0.04] hover:-translate-y-[1px]"
              >
                <div className="text-[14px] text-[#e3ecff] leading-relaxed mb-2">
                  {h.text}
                </div>
                <div className="flex items-center gap-4 flex-wrap">
                  <span className="mono text-[10px] uppercase tracking-[0.22em] text-cyan-300/80 flex items-center gap-1.5">
                    <Bookmark size={10} /> {h.mapTitle}
                  </span>
                  {h.fileName && (
                    <span className="mono text-[10px] uppercase tracking-[0.22em] text-[#6c7aa3] flex items-center gap-1.5">
                      <FileText size={10} /> {h.fileName}
                    </span>
                  )}
                  {h.pageNumber != null && (
                    <span className="mono text-[10px] uppercase tracking-[0.22em] text-[#566187]">
                      p. {h.pageNumber}
                    </span>
                  )}
                  <span className="mono text-[10px] uppercase tracking-[0.22em] text-[#566187]">
                    {formatTs(h.ts)}
                  </span>
                  <div className="ml-auto flex items-center gap-2">
                    <button
                      onClick={(e) => { e.stopPropagation(); navigator.clipboard?.writeText(h.text); toast("Copied"); }}
                      data-testid="highlights-copy"
                      className="text-[#566187] hover:text-cyan-300 p-1 rounded"
                      title="Copy"
                    >
                      <Copy size={12} />
                    </button>
                    <ExternalLink size={12} className="text-[#566187] group-hover:text-cyan-300 transition" />
                  </div>
                </div>
              </li>
            ))}
          </ul>
        )}
      </main>
    </div>
  );
}

function EmptyHero({ onGo }) {
  return (
    <div
      data-testid="highlights-empty"
      className="text-center py-16 rounded-2xl border border-dashed border-white/10 bg-white/[0.01]"
    >
      <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-cyan-400/20 to-violet-500/10 border border-cyan-400/40 grid place-items-center mx-auto mb-5">
        <Highlighter size={26} className="text-cyan-200" />
      </div>
      <div className="text-xl font-bold text-white mb-2">No highlights yet</div>
      <div className="text-[13px] text-[#9aa7c7] max-w-md mx-auto mb-5">
        Open a PDF in the Reader, select a passage, and tap <span className="text-cyan-300">+ Node</span>. Your ledger will start building itself.
      </div>
      <button
        onClick={onGo}
        data-testid="highlights-empty-cta"
        className="cta-pill px-5 py-2.5 text-[13px]"
      >
        Open the PDF Reader →
      </button>
    </div>
  );
}

function formatTs(ts) {
  if (!ts) return "";
  const diff = Date.now() - ts;
  const min = Math.floor(diff / 60000);
  if (min < 1) return "just now";
  if (min < 60) return `${min} min ago`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr}h ago`;
  const d = Math.floor(hr / 24);
  if (d < 30) return `${d}d ago`;
  return new Date(ts).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}
